version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: raul-albanil-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: presupuestos_db
    ports:
      - "5433:5432" #ponemos el 5433 ya que el 5432 lo tengo ocupado por planeta viaje
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: